### ISSUE TITLE
Add License/Modpack policy

### ISSUE THREAD

**Issue by UnPure** [gbl/AntiGhost#1]
Hey there.
I'm currently working on a small modpack and i would like to add AntiGhost to it.
I cant find any informations about your Modpack Policy or a License about your mod.
Do you allow your mod to be part of modpacks? If yes, could you add a small part of text to the curseforge page?

Also as a small question about the mod itself. Is it requiered on both (Client & Server) or only on the client side?

**Comment by gbl** [comment]
Hi Daniel,

the mod is distributed under the GPL license, which basically means you can take it, distribute it, and change the code as you want as long as you offer to provide the source code. As the source code is on my github page, including a link to that page in a readme somewhere will be sufficient. (And the curseforge page mentions GPL; it's not possible to use the GPL and forbid including the mod in a pack).

The mod is a client side mod, it will work with vanilla or unmodded spigot servers as well. That was actually one of the objectives when I made it, I wanted it to be usable for players without the server owner having to do anything.

Guntram


Am 21. August 2017 13:50:14 MESZ, schrieb "Daniel B." <notifications@github.com>:
>Hey there.
>I'm currently working on a small modpack and i would like to add
>AntiGhost to it.
>I cant find any informations about your Modpack Policy or a License
>about your mod.
>Do you allow your mod to be part of modpacks? If yes, could you add a
>small part of text to the curseforge page?
>
>Also as a small question about the mod itself. Is it requiered on both
>(Client & Server) or only on the client side?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gbl/AntiGhost/issues/1

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by UnPure** [comment]
The curseforge page has "All Rights Reserved" as the license, thats why i'm asking.
I will use this issue as a link back to the license when asked for.
Thank you!
