### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by crystall1nedev** [gbl/AntiGhost#16]
I've tried compiling on Manjaro 21 and Ubuntu 20.04, and I still get the same results. Gradle fails with:

```
* What went wrong:
A problem occurred configuring root project 'AntiGhost'.
> apiKey not set for project 273279
```
I checked over the steps to compile as written in your COMPILING.MD file and nothing changed :/

**Comment by crystall1nedev** [comment]
Found the problem:

```
curseforge {
    apiKey = System.getenv("CURSEFORGE_TOKEN")
    project {
	id = '273279'
	releaseType = 'release'
	addGameVersion("${Versions['minecraft_version']}")
	addGameVersion("Java 8")
	addGameVersion("Fabric")

	mainArtifact(remapJar)
    }
    // afterEvaluate {
	    // logger.quiet("remapJar:", remapJar)
	    // mainArtifact(remapJar.jar)
	    // uploadTask.dependsOn(remapJar)
    // }
    options {
    	// debug = true
	forgeGradleIntegration = false
    }
}
```

I'm guessing this is specific to your Curseforge uploading?

**Comment by gbl** [comment]
Yes, that's the curseforge plugin, which unfortunately bails if the apikey isn't set, even if you just compile and don't upload to curseforge. You can set the apikey to "whatever" to compile it. Guess I'll have to put some default apikey there if CURSEFORGE_TOKEN isn't set so people can at least compile, as it doesn't seem like the author of the CF plugin is going to fix that anytime soon.

**Comment by crystall1nedev** [comment]
I was actually able to compile when I deleted those lines.
