### ISSUE TITLE
Need it for 1.16.5 Forge Please Update using "Prefabs" mod causing chunk ghosting.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [gbl/AntiGhost#17]
Using the prefabs mod has started causing chunk ghosting please update to forge 1.16.5

**Comment by gbl** [comment]
The 1.16.4 version works for 1.16.5 as well.

**Comment by P3rf3ctXZer0** [comment]
ITS FABRIC

**Comment by P3rf3ctXZer0** [comment]
https://www.curseforge.com/minecraft/mc-mods/antighost

**Comment by P3rf3ctXZer0** [comment]
Nevermind curse strikes again. Sorry for bothering you.
