### ISSUE TITLE
Crash after experiencing the ghost bug and re-entering world – java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Dimentive** [gbl/AntiGhost#2]
When I broke a wireless charging antenna from Ender IO with a fast pickaxe, it caused the ghost bug. At this point, I did not have [AntiGhost](https://minecraft.curseforge.com/projects/antighost) installed. I exited my world, restarted my client, and installed AntiGhost so I wouldn’t have to exit the world and restart my client the next time that this happens (which I do because of [this problem](https://www.reddit.com/r/FeedTheBeastCrashes/comments/bcy19g/game_always_freezes_when_exiting_and_entering_any/)). When I got back in the game—this time with AntiGhost installed, as mentioned—I entered my world again. Immediately after entering the world, I crashed before getting the chance to do anything. Uninstalling AntiGhost fixed the issue, as I was able to enter the world without crashing after I exited the game, removed AntiGhost, re-launched the game, and entered my world again.

Crash report: https://pastebin.com/raw/qjFA8Bg5

#### Versions

* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.64](https://minecraft.curseforge.com/projects/enigmatica2/files/2697889), latest, with some mods added)
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **AntiGhost:** [1.1](https://minecraft.curseforge.com/projects/antighost/files/2458392) (latest)

**Comment by gbl** [comment]
I'm sorry, but I'm afraid I can't help you much with that. Looking at the crash report, the crash happens in
```
java.util.ConcurrentModificationException
    at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:401)
    at net.minecraft.client.audio.SoundManager.updateAllSounds(SoundManager.java:252)
    at net.minecraft.client.audio.SoundHandler.update(SoundHandler.java:293)

```
where updateAllSounds is the method that sends, for all sounds that are currently playing, new data to the sound subsystem. The CME looks like some other mod is adding or deleting a sound while that happens, which would need to happen on a different thread (unless a mod hooked into one of the methods that are called from updateAllSounds, but there's not many of them which makes that quite unlikely).
AntiGhost doesn't do anything that has anything to do with sounds, so I don't really think this is at fault here. I'd rather assume there is some race condition with a different mod, that happens only once in a while,when that other mod is adding a sound right while MC is trying to play the existing ones, and if you enter the world again, it'll work, with or without AntiGhost installed.

After I downloaded your mod pack and started it, I understand why you don't like restarting the client - it takes forever - but I'd still suggest to try again once or twice.

Also, the playSound() method has a check for the master sound volume, and doesn't play a sound if that volume is zero. It could be worth a try to set the master volume to zero before entering a world, and possibly set it back to what you like when the world is loaded; maybe that'll even work around your world enter bug (which, by the way, I didn't have when I tried your modpack; but I didn't add any other mods (except Antighost)).
