### ISSUE TITLE
Fabric 1.17.1 Crash mentioning Antighost

### ISSUE THREAD

**Issue by DatrixTHLK** [gbl/AntiGhost#23]
Hi,

I've had a crash with Antighost

Crash Log: https://bytebin.lucko.me/MbRJnAsAXO

Minecraft: 1.17.1
Fabric: 0.12.5
Antighost: fabric0.36.1-1.1.4

Not sure exactly why.

**Comment by gbl** [comment]
Not sure why the last line suspects AntiGhost, but that's wrong ...

The top of the stack trace says
```
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61)
	at com.alcatrazescapee.cyanide.codec.MixinHooks.readRegistries(MixinHooks.java:67)
	at net.minecraft.util.registry.DynamicRegistryManager.handler$bgg000$loadCollectingErrors(DynamicRegistryManager:531)
```

and all the lines above that hint at some problems when reading some json definition files, which is consistent with the `readRegistries` method name.

So I guess you might want to remove or reinstall cyanide: Cyanide (Fabric) 1.2.0 as that is the mod that was active when the crash occured.

**Comment by DatrixTHLK** [comment]
I see thanks for the help and response
