### ISSUE TITLE
Idea: Rename `/ghost` to `/cghost` to match ClientCommands naming convention

### ISSUE THREAD

**Issue by James103** [gbl/AntiGhost#25]
https://github.com/gbl/AntiGhost/blob/9d803da143e36fb2ce273fb00872f0cad01fa47b/src/main/java/de/guntram/mcmod/antighost/AntiGhost.java#L32-L35

[Earthcomputer/ClientCommands](https://github.com/Earthcomputer/clientcommands) adds several commands, all of which start with the letter `c` to denote that it is a client side only command. As this mod adds a client-side command `/ghost`, it may be renamed to `/cghost` for consistency.

The rename could either be an alias, whereby `/cghost` aliases `/ghost`, or it could be a full rename, where `/ghost` is no longer a command added by the mod because that command was renamed to `/cghost`.

**Comment by gbl** [comment]
The command has been /ghost ever since the mod came out in 2017. I won't change that because some other mod, that came out much later, uses some kind of standard for itself.
