### ISSUE TITLE
Not compatible with Searchable Containers by:  Areuthreateningme on curseforge

### ISSUE THREAD

**Issue by aak54261** [gbl/AntiGhost#26]
The magnifying glass icon overlaps one of the arrows from the Searchable containers mod.
Not sure how you would change it but maybe us players can have an option to change the position of the magnifying glass. or something
Images: 
![image](https://user-images.githubusercontent.com/93615617/148087209-2186c16f-1c97-4f1b-9d78-a4d803e3a949.png)
![image](https://user-images.githubusercontent.com/93615617/148087274-90386263-dc15-46d8-9576-7861fb128bf1.png)

**Comment by gbl** [comment]
Erm, that magnifying glass doesn't come from Antighost.

**Comment by aak54261** [comment]
dang im stupid
wrong mod

**Comment by aak54261** [comment]
it was for the chest tracker sorry
