### ISSUE TITLE
1.7.10 Backport

### ISSUE THREAD

**Issue by Jerome226** [gbl/AntiGhost#28]
I see there a 1.8.9 backport, is there any chances to port to 1.7.10 too?

**Comment by jimmon89** [comment]
i'd like to second this
i play a hardcore pack called "Gregtech: New Horizons" and the block ghosting is terrible for me while mining, especially in the nether with how soft netherrack happens to be
and a mod like this would be a godsend

**Comment by gbl** [comment]
Very unlikely, as that version is very old and it'd probably be a pain to set everything up. But I'll leave this issue open for now in case someone wants to create a port.

**Comment by jimmon89** [comment]
i was able to use the version of gradle wrapper from the forge source kit to set up a dev environment
but my knowledge of java is very rudimentary and i have no idea how to fix the problems that cause it to fail to compile for 1.7.10

--edit--
i went ahead and forked the repo and made a 1.7.10 branch with my changes to build.gradle right here
[https://github.com/jimmon89/AntiGhost/tree/forge_1_7_10](https://github.com/jimmon89/AntiGhost/tree/forge_1_7_10)

--edit-2--
if anyone would like to take a crack at it feel free to fork mine and have at it :)
or make your own version of build.gradle if you're so inclined
