### ISSUE TITLE
Couldn't execute entrypoint stage 'client', causing a crash upon launching

### ISSUE THREAD

**Issue by NaiNonTH** [gbl/AntiGhost#31]
I'll let the crash report and the log below describe the crash.

**Crash Report**
* [crash-2022-06-12_14.53.11-client.txt](https://github.com/gbl/AntiGhost/files/8885440/crash-2022-06-12_14.53.11-client.txt)

**Log**
* [latest.log](https://github.com/gbl/AntiGhost/files/8885441/latest.log)

**Comment by somebirby** [comment]
I get the same crash as well.

**Comment by gbl** [comment]
Yes, unfortunately there was a change in Fabric that caused all my mods that used client side commands to break. Just published a new version.

**Comment by NaiNonTH** [comment]
Cool
