### ISSUE TITLE
Curseforge Tag

### ISSUE THREAD

**Issue by Thunder-Nova** [gbl/AntiGhost#33]
I had to manually download the forge-1.18.1 mod from the curseforge website to test it on a 1.18.2 forge modpack: All the mod 7.

Since they added the Twilight forest mod, I started to see more often blocks that are ghost glitched.

You might need to add the 1.18.2 tag to your 1.18.1 mod since it works on 1.18.2

The Tag makes it possible for the mod to be manually downloaded from the platforms.

**Comment by gbl** [comment]
Thanks for noticing, changed!
