### ISSUE TITLE
Issues with 1.19.3

### ISSUE THREAD

**Issue by mustafakamran98** [gbl/AntiGhost#36]
Using 1.19.3 with Fabric API 0.14.11 and PrismLauncher 5.2 seems to cause the game to loop before getting to the title screen. The text for each menu button is also just a bunch of squares.

Logs: https://mclo.gs/l1Iy5XG

![image](https://user-images.githubusercontent.com/27556124/206353609-739b0fc3-235c-4c21-b30e-8817e1d50e8a.png)

**Comment by mustafakamran98** [comment]
Forgot the version of AntiGhost: antighost-1.19.1-fabric0.58.5-1.1.5

**Comment by mustafakamran98** [comment]
Testing with the 22w45a release of this mod and the game launches and plays. Not sure if I can really test it properly since I have only been able to test it on a single-player world

**Comment by gbl** [comment]
Yes, there have been some incompatible changes between 1.19.1 and 22w45a that caused this problem. The 22w45a version of the mod should work, as should the 1.19.3 version which I just published.
