### ISSUE TITLE
1.20 when?

### ISSUE THREAD

**Issue by Santiag09** [gbl/AntiGhost#41]
is there an estimated date of release yet or anything? Thanks!

**Comment by NetheriteBowl** [comment]
You said what I wanted to say 😂, looking forward to the author's update to **1.20**

**Comment by SAJewers** [comment]
The mod already works for 1.20, you don't have to do anything.

**Comment by gbl** [comment]
Older versions should work, but there's a new 1.20/1.21 version out now.
