### ISSUE TITLE
Forge 1.20.1 Support?

### ISSUE THREAD

**Issue by PlayfulPiano** [gbl/AntiGhost#49]
This has been a super useful mod for me back when I was playing fabric 1.18.2, but I recently switched over to forge 1.20.1. Wanted to ask if you could consider porting this over whenever you have the time to do so. Thanks!

**Comment by gbl** [comment]
Sorry, but I won't do any more Forge updates. It's hard enough to keep the Fabric versions up to date as I'm not playing MC anymore; Forge has always been happy to introduce breaking changes within versions, and the split between Forge and NeoForge doesn't make things easier.
