### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by 5HT2** [gbl/AntiGhost#6]
Hi, would you mind releasing this under a license? If a repository on Github has no license that means that you hold all rights and we can't do anything with the code, other then look at it. 

I would recommend using MIT or if you don't want something as permissive, LGPLv3, as I imagine this would be used as a library in mods.

**Comment by 5HT2** [comment]
Oh, I just saw issue #1. I'm not sure how legally binding a comment on a github issue is, but in order for this to properly be licensed under GPL you need to leave a LICENSE or LICENSE.md file somewhere in the repository @gbl. Feel free to close this once you've done that.

**Comment by gbl** [comment]
Will do that at some point, but it's quite some work as I'll have to do that for every branch as each of the forge/fabric and MC versions have their separate branches. But I hereby do grant permission to you to use the source code of this mod, in all of its current versions, under the GPL.

**Comment by 5HT2** [comment]
Oh I see. Thank you!

**Comment by gbl** [comment]
The new versions all have a MIT LICENSE file in the jar, and in the root folder as well.

**Comment by 5HT2** [comment]
Thank you!
