### ISSUE TITLE
4 block radius

### ISSUE THREAD

**Issue by willperes** [gbl/AntiGhost#7]
Hello! First of all I would like to say that your mod helped me a lot, thank vou.

I would like to know if there is a way to change the radius to fix 4 blocks above the player. Currently it fix only 3 blocks above the player. And btw I use the 1.10.2 Minecraft version.

**Comment by gbl** [comment]
Sorry, no, the number of packets sent to the server is already high enough. And honestly, 1.10.2 is just too old for me to still support.
