### ISSUE TITLE
Invalid "NOmixins" entry in mod json

### ISSUE THREAD

**Issue by Fourmisain** [gbl/AntiGhost#9]
This entry:
https://github.com/gbl/AntiGhost/blob/a91125703675e8e4c9264a970c7ac3fe928283c6/src/main/resources/fabric.mod.json#L16-L18
causes a warning:
```
[21:09:19] [ForkJoinPool-1-worker-23/WARN]: The mod "antighost" contains invalid entries in its mod json:
- Unsupported root entry "NOmixins" at line 20 column 13
```
The entry can simply be removed as it's not functional either way.
The file `mixins.antighost.json` can be removed as well (it points to a non-existing refmap, so it doesn't look like it was ever used in any way).

**Comment by gbl** [comment]
Thanks, removed in 1.16.4 version
